name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install 64 bit dependencies
      run: |
        sudo apt-get build-dep -y wine-development
        sudo apt-get install -y libsane-dev libv4l-dev libgphoto2-dev libcapi20-dev mingw-w64 libkrb5-dev winbind libvulkan-dev libsdl2-dev libgnutls28-dev libcups2-dev libgstreamer-plugins-base1.0-dev libgl1-mesa-dri libxslt1-dev libgtk-3-dev libva-dev
    - name: Install 32 bit dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt-get build-dep -y wine-development -a i386 
        sudo apt-get install -y gcc-multilib libsane-dev:i386 libv4l-dev:i386 libgphoto2-dev:i386 libcapi20-dev:i386 libkrb5-dev:i386 libvulkan-dev:i386 libgnutls28-dev:i386 libcups2-dev:i386 libgstreamer-plugins-base1.0-dev:i386 libgl1-mesa-dri:i386 libxslt1-dev:i386 libgtk-3-dev:i386 libva-dev:i386 libvkd3d-dev:i386 libglu1-mesa-dev:i386 libosmesa6-dev:i386 libpcap0.8-dev:i386 libncurses-dev:i386 liblcms2-dev:i386 libpulse-dev:i386 libfaudio-dev:i386 libgsm1-dev:i386 libmpg123-dev:i386 libopenal-dev:i386 libldap-dev:i386 ocl-icd-opencl-dev:i386
    - name: configure
      run: |
         mkdir wine64-build wine32-build
    - name: make
      run: |
        cd wine64-build && ../configure -C CFLAGS="-g -Og" CROSSCFLAGS="-g -Og" --enable-win64 && make && cd ../wine32-build && ../configure -C CFLAGS="-g -Og" CROSSCFLAGS="-g -Og" --with-wine64=../wine64-build && make
